/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChambresRouteImport } from './routes/chambres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as LocalisationRouteImport } from './routes/localisation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresRoute = ChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalisationRoute = LocalisationRouteImport.update({
  id: '/localisation',
  path: '/localisation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/localisation': typeof LocalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/localisation': typeof LocalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/localisation': typeof LocalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chambres'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/localisation'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chambres'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/localisation'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/chambres'
    | '/contact'
    | '/faq'
    | '/galerie'
    | '/localisation'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChambresRoute: typeof ChambresRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  LocalisationRoute: typeof LocalisationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres': {
      id: '/chambres'
      path: '/chambres'
      fullPath: '/chambres'
      preLoaderRoute: typeof ChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localisation': {
      id: '/localisation'
      path: '/localisation'
      fullPath: '/localisation'
      preLoaderRoute: typeof LocalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChambresRoute: ChambresRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  LocalisationRoute: LocalisationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
