/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChambresRouteImport } from './routes/chambres'
import { Route as LocalisationRouteImport } from './routes/localisation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresRoute = ChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalisationRoute = LocalisationRouteImport.update({
  id: '/localisation',
  path: '/localisation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/localisation': typeof LocalisationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/localisation': typeof LocalisationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/localisation': typeof LocalisationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chambres' | '/localisation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chambres' | '/localisation'
  id: '__root__' | '/' | '/chambres' | '/localisation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChambresRoute: typeof ChambresRoute
  LocalisationRoute: typeof LocalisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres': {
      id: '/chambres'
      path: '/chambres'
      fullPath: '/chambres'
      preLoaderRoute: typeof ChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localisation': {
      id: '/localisation'
      path: '/localisation'
      fullPath: '/localisation'
      preLoaderRoute: typeof LocalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChambresRoute: ChambresRoute,
  LocalisationRoute: LocalisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
